export { default as Main } from "./main/Main";
export { default as ProfileEdit } from "./profile-edit/ProfileEdit";
export { default as Register } from "./register/Register";
export { default as FreeBoard } from "./free-board/FreeBoard";
export { default as StudentCheck } from "./register/subpages/StudentCheck";
export { default as ProfileRegister } from "./register/subpages/ProfileRegister";
export { default as PwRegister } from "./register/subpages/PwRegister";
export { default as EmailCheck } from "./register/subpages/EmailCheck";
export { default as ProfileDetail } from "./profile-detail/ProfileDetail";
